name: Build container images

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-ecr-images:
    name: 'Build and push ECR images'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # required for obtaining the OIDC JWT from GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN_FOR_OIDC }}
        role-session-name: docker-build-in-gh-actions
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      uses: aws-actions/amazon-ecr-login@v2.0.1
      with:
        registry-type: public

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Set Docker tag
      id: set_tag
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        else
          TAG="${GITHUB_SHA}"
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build, tag, and push docker image to Amazon ECR Public
      uses: docker/bake-action@v6.10.0
      env:
        REGISTRY: public.ecr.aws
        TAG: ${{ env.TAG }}
      with:
        source: .
        push: true
